# Docker Compose configuration for running Python
#
# Usage:
#   docker compose run --rm python
#   docker compose run --rm python script.py
#   docker compose run --rm python --help
#
# This will run Python on your codebase with default settings

services:
  python:
    image: ragedunicorn/python:${PYTHON_VERSION:-latest}
    container_name: python
    volumes:
      - ./app:/app
    working_dir: /app
    stdin_open: true
    tty: true
    environment:
      - PYTHONUNBUFFERED=1
      - TERM=xterm-256color
